import 'package:flutter/material.dart';
import 'package:islami/Ui/home/hadeth/hadeet_name.dart';

class HadethTab extends StatelessWidget {
  List<String> hadethList = [
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h11',
    'h111',
    'h1111',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h11',
    'h111',
    'h1111',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h11',
    'h111',
    'h1111',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h1',
    'h11',
    'h111',
    'h1111',
    'h11111',
    'h1111111',
    'h11111111',
    'h111111111',
    'h1111111111'
  ];

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: double.infinity,
          height: 1,
          color: Theme.of(context).primaryColor,
          margin: EdgeInsets.symmetric(vertical: 4),
        ),
        Text('Hadeeth Name',
            style: TextStyle(fontSize: 24, fontWeight: FontWeight.bold)),
        Container(
          width: double.infinity,
          height: 1,
          color: Theme.of(context).primaryColor,
          margin: EdgeInsets.symmetric(vertical: 4),
        ),
        Expanded(
            child: ListView.separated(
          itemBuilder: (context, index) {
            return HadethNameWidget(hadethList[index], index);
          },
          itemCount: hadethList.length,
          separatorBuilder: (context, index) {
            return Container(
              width: double.infinity,
              height: 1,
              color: Theme.of(context).primaryColor,
              margin: EdgeInsets.symmetric(vertical: 4),
            );
          },
        ))
      ],
    );
  }
}
